schema:
  - "../../**/*.graphql"
exec:
  filename: schema/schema.go
model:
  filename: schema/model.go
autobind:
  - github.com/Wondertan/trapezza-go/types
  - github.com/Wondertan/trapezza-go/trapezza
  - github.com/Wondertan/trapezza-go/restaurant

models:
  TrapezzaSession:
    model: types.Trapezza
  GroupItem:
    model: types.GroupItem
  Client:
    model: types.Client
  Call:
    model: types.Call
  Group:
    model: types.Group
  Item:
    model: types.Item
  TrapezzaSessionUpdate:
    model: trapezza.Update
  TrapezzaSessionEvents:
    model: trapezza.Event
  ChangeWaiter:
    model: trapezza.ChangeWaiterEvent
  ChangePayer:
    model: trapezza.ChangePayerEvent
  NewGroup:
    model: trapezza.NewGroupEvent
  AddItems:
    model: trapezza.AddItemsEvent
  RemoveItem:
    model: trapezza.RemoveItemEvent
  SplitItem:
    model: trapezza.SplitItemEvent
  JoinGroup:
    model: trapezza.JoinGroupEvent
  CheckoutClient:
    model: trapezza.CheckoutClientEvent
  CheckoutPayer:
    model: trapezza.CheckoutPayerEvent
  WaiterCall:
    model: trapezza.WaiterCallEvent
  RestaurantEvents:
    model: restaurant.Event
  NewTrapezzaSession:
    model: restaurant.NewTrapezzaSessionEvent
  EndTrapezzaSession:
    model: restaurant.EndTrapezzaSessionEvent