schema:
  - "../../**/*.graphql"
exec:
  filename: schema/schema.go
model:
  filename: schema/model.go
autobind:
  - github.com/Wondertan/trapezza-go/types
  - github.com/Wondertan/trapezza-go/trapezza
  - github.com/Wondertan/trapezza-go/restaurant

models:
  TrapezzaSession:
    model: types.Trapezza
  OrderItem:
    model: types.OrderItem
  ClientOrder:
    model: types.ClientOrder
  Call:
    model: types.Call
  GroupOrder:
    model: types.GroupOrder
  Item:
    model: types.Item
  TrapezzaSessionUpdate:
    model: trapezza.Update
  TrapezzaSessionEvents:
    model: trapezza.Event
  ChangeWaiter:
    model: trapezza.ChangeWaiterEvent
  ChangePayer:
    model: trapezza.ChangePayerEvent
  NewGroupOrder:
    model: trapezza.NewGroupOrderEvent
  AddItems:
    model: trapezza.AddItemsEvent
  RemoveItem:
    model: trapezza.RemoveItemEvent
  SplitItem:
    model: trapezza.SplitItemEvent
  JoinGroupOrder:
    model: trapezza.JoinGroupOrderEvent
  CheckoutClient:
    model: trapezza.CheckoutClientEvent
  CheckoutPayer:
    model: trapezza.CheckoutPayerEvent
  WaiterCall:
    model: trapezza.WaiterCallEvent
  RestaurantEvents:
    model: restaurant.Event
  NewTrapezzaSession:
    model: restaurant.NewTrapezzaSessionEvent
  EndTrapezzaSession:
    model: restaurant.EndTrapezzaSessionEvent