// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schema

type Order struct {
	Client *string   `json:"client"`
	Items  []*string `json:"items"`
}

type Session struct {
	ID     *string  `json:"id"`
	Waiter *string  `json:"waiter"`
	Table  *string  `json:"table"`
	Orders []*Order `json:"orders"`
}
