schema:
  - schema.graphql
exec:
  filename: schema/schema.go
model:
  filename: schema/model.go
autobind:
  - github.com/Wondertan/trapezza-go/session

models:
  ID:
    model: session.ID
  Session:
    model: session.State
  Order:
    model: session.Order
  EventType:
    model: session.EventType
  Event:
    model: session.Event
  WaiterEvent:
    model: session.WaiterEvent
  ClientEvent:
    model: session.ClientEvent
  TableEvent:
    model: session.TableEvent
  ItemEvent:
    model: session.ItemEvent